controllers:
    resource: ../src/Controller/
    type: attribute

app_post_index:
    path: /post
    controller: App\Controller\PostController::index
    methods: GET

app_post_new:
    path: /post/new
    controller: App\Controller\PostController::new
    methods: POST

app_post_show:
    path: /post/{id}
    controller: App\Controller\PostController::show
    methods: GET

app_post_edit:
    path: /post/{id}/edit
    controller: App\Controller\PostController::edit
    methods: PUT

app_post_delete:
    path: /post/{id}
    controller: App\Controller\PostController::delete
    methods: DELETE

app_post_comments:
    path: /post/{postId}/comments
    controller: App\Controller\PostController::comments
    methods: GET

app_comment_index:
    path: /comments
    controller: App\Controller\CommentController::index
    methods: ['GET']

app_comment_new:
    path: /comment/new/{postId}
    controller: App\Controller\CommentController::new
    methods: ['POST']

app_comment_show:
    path: /comment/{id}
    controller: App\Controller\CommentController::show
    methods: ['GET']

app_comment_show_post:
    path: /comment/show/{postId}
    controller: App\Controller\CommentController::showComments
    methods: ['GET']

app_comment_delete:
    path: /comment/{id}
    controller: App\Controller\CommentController::delete
    methods: ['DELETE']
app_user_index:
  path: /users
  controller: 'App\Controller\UserController::index'
  methods: ['GET']

app_user_new:
  path: /users/new
  controller: 'App\Controller\UserController::new'
  methods: ['POST']

app_user_show:
  path: /users/{id}
  controller: 'App\Controller\UserController::show'
  methods: ['GET']

app_user_edit:
  path: /users/{id}/edit
  controller: 'App\Controller\UserController::edit'
  methods: ['GET', 'POST']

app_user_delete:
  path: /users/{id}
  controller: 'App\Controller\UserController::delete'
  methods: ['DELETE']
app_login:
    path: /login
    controller: App\Controller\AuthController::login

app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout

home:
    path: /
    controller: App\Controller\HomeController::index

etudiant_index:
    path: /etudiant/
    controller: App\Controller\EtudiantController::index
    methods: GET

etudiant_new:
    path: /etudiant/new
    controller: App\Controller\EtudiantController::new
    methods: POST

etudiant_show:
    path: /etudiant/{id}
    controller: App\Controller\EtudiantController::show
    methods: GET

etudiant_edit:
    path: /etudiant/{id}/edit
    controller: App\Controller\EtudiantController::edit
    methods: POST

etudiant_delete:
    path: /etudiant/{id}
    controller: App\Controller\EtudiantController::delete
    methods: DELETE
app_enseignant_index:
    path: /enseignant/
    controller: App\Controller\EnseignantController::index
    methods: GET

app_enseignant_new:
    path: /enseignant/new
    controller: App\Controller\EnseignantController::new
    methods: POST

app_enseignant_show:
    path: /enseignant/{id}
    controller: App\Controller\EnseignantController::show
    methods: GET

app_enseignant_edit:
    path: /enseignant/{id}/edit
    controller: App\Controller\EnseignantController::edit
    methods: PUT

app_enseignant_delete:
    path: /enseignant/{id}
    controller: App\Controller\EnseignantController::delete
    methods: DELETE
app_administrateur_index:
    path: /administrateur/
    controller: App\Controller\AdministrateurController::index
    methods: GET

app_administrateur_new:
    path: /administrateur/new
    controller: App\Controller\AdministrateurController::new
    methods: POST

app_administrateur_show:
    path: /administrateur/{id}
    controller: App\Controller\AdministrateurController::show
    methods: GET

app_administrateur_edit:
    path: /administrateur/{id}/edit
    controller: App\Controller\AdministrateurController::edit
    methods: PUT

app_administrateur_delete:
    path: /administrateur/{id}
    controller: App\Controller\AdministrateurController::delete
    methods: DELETE
app_like_index:
    path: /like/
    controller: App\Controller\LikeController::index
    methods: GET

app_like_new:
    path: /like/new
    controller: App\Controller\LikeController::new
    methods: POST

app_like_show:
    path: /like/{id}
    controller: App\Controller\LikeController::show
    methods: GET

app_like_delete:
    path: /like/{id}
    controller: App\Controller\LikeController::delete
    methods: DELETE
app_file_index:
    path: /file
    controller: 'App\Controller\FileController::index'
    methods: ['GET']

app_file_new:
    path: /file/new
    controller: 'App\Controller\FileController::new'
    methods: ['POST']

app_file_show:
    path: /file/{id}
    controller: 'App\Controller\FileController::show'
    methods: ['GET']

app_file_delete:
    path: /file/{id}
    controller: 'App\Controller\FileController::delete'
    methods: ['DELETE']
app_user_get_by_email:
    path: /user/email
    controller: 'App\Controller\UserController::getUserByEmail'
    methods: [GET]